import type { Metadata } from "next";
import { Questrial, Orbitron } from "next/font/google";
import "./globals.css";
import { AppProviders } from "./app-providers";

const questrial = Questrial({
  subsets: ["latin"],
  variable: "--font-questrial",
  weight: "400", // Questrial only supports weight 400
  display: "swap",
});

const kodeMono = Orbitron({
  subsets: ["latin"],
  variable: "--font-kode-mono",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${questrial.variable} ${kodeMono.variable} antialiased`}
      >
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
